import { ShopifyGlyph } from "@/components/icons";
import type { Project, ProjectLogo } from "./data";

const SHOPIFY_GLYPH_LOGO: ProjectLogo = {
  kind: "image",
  src: ShopifyGlyph,
  alt: "shopify glyph",
};

export const SHOPIFY_STORES: Project[] = [
  {
    id: "decodeage",
    title: "DecodeAge",
    summary:
      "Revamped entire websites and built new ones from scratch based on Figma designs. Developed visually appealing and interactive user interfaces by writing clean and efficient Shopify Liquid templates, HTML, CSS, and JavaScript code.",
    status: "active",
    periodLabel: "Jan 2024 - Present",
    technologies: [
      "HTML5",
      "CSS",
      "JavaScript",
      "Shopify Plus",
      "Liquid Template Language",
      "Shopify Ecosystem",
      "Shopify Flows",
      "App & Tools Integrations",
    ],
    primaryUrl: "https://decodeage.com/",
    logo: SHOPIFY_GLYPH_LOGO,
    links: [{ kind: "live", label: "Website", url: "https://decodeage.com/", iconKey: "globe" }],
    previewImage: "https://i.ibb.co/FbtGr4r9/Decode-Age.png",
  },
  {
    id: "halemons",
    title: "Halemons",
    summary:
      "Customized existing Shopify themes to align perfectly with clients' branding by tailoring layouts, colors, fonts, and imagery.",
    status: "archived",
    periodLabel: "2023 - 2024",
    technologies: [
      "HTML5",
      "CSS",
      "JavaScript",
      "Shopify",
      "Shopify Customization",
      "Liquid Template Language",
      "Shopify Ecosystem",
    ],
    primaryUrl: "https://halemons.com/",
    logo: SHOPIFY_GLYPH_LOGO,
    links: [{ kind: "live", label: "Website", url: "https://halemons.com/", iconKey: "globe" }],
    previewImage: "https://i.ibb.co/Pv2hbQFX/Halemons.png",
  },
  {
    id: "vivanti-london",
    title: "Vivanti London",
    summary:
      "Resolved UI/UX issues on the Product Detail Page (PDP) caused by language translation bugs. Improved and optimized the PDP for better performance and user experience.",
    status: "active",
    periodLabel: "2025",
    technologies: [
      "Shopify",
      "Custom Development",
      "Liquid Template Language",
      "Liquid Schema Updates",
      "Site Optimization",
      "Language Translation Bug Fix",
      "App Fix",
    ],
    primaryUrl: "https://vivantilondon.com/",
    logo: SHOPIFY_GLYPH_LOGO,
    links: [{ kind: "live", label: "Website", url: "https://vivantilondon.com/", iconKey: "globe" }],
    previewImage: "https://i.ibb.co/W4dJWKcT/Vivanti-London.png",
  },
  {
    id: "kavarsa",
    title: "Kavarsa",
    summary:
      "Designed and developed a store from scratch, crafting the UI/UX and implementing complete customization to deliver a unique and tailored eCommerce experience.",
    status: "archived",
    periodLabel: "2024",
    technologies: [
      "HTML5",
      "CSS",
      "JavaScript",
      "Shopify",
      "Shopify Customization",
      "Liquid Template Language",
    ],
    primaryUrl: "https://kavarsa.com/",
    logo: SHOPIFY_GLYPH_LOGO,
    links: [{ kind: "live", label: "Website", url: "https://kavarsa.com/", iconKey: "globe" }],
    previewImage: "https://i.ibb.co/3JDm2nv/Kavarsa.png",
  },
  {
    id: "nuvijewels",
    title: "Nuvijewels",
    summary:
      "Customising Shopify theme to match the client's branding, including layout, colours, fonts, and imagery.",
    status: "active",
    periodLabel: "2023",
    technologies: [
      "HTML5",
      "CSS",
      "JavaScript",
      "Shopify",
      "Shopify Customization",
      "Liquid Template Language",
      "Site Optimization",
    ],
    primaryUrl: "https://nuvijewels.com/",
    logo: SHOPIFY_GLYPH_LOGO,
    links: [{ kind: "live", label: "Website", url: "https://nuvijewels.com/", iconKey: "globe" }],
    previewImage: "https://i.ibb.co/Mkd3hXz3/Nuvi.png",
  },
  {
    id: "slc",
    title: "SLC",
    summary:
      "Designed and developed a store from scratch, crafting the UI/UX and implementing complete customization to deliver a unique and tailored eCommerce experience.",
    status: "active",
    periodLabel: "2024 - 2025",
    technologies: [
      "HTML5",
      "CSS",
      "JavaScript",
      "Shopify",
      "Shopify Customization",
      "Liquid Template Language",
      "App Integrations",
      "Site Optimization",
    ],
    primaryUrl: "https://shopslc.com/",
    logo: SHOPIFY_GLYPH_LOGO,
    links: [{ kind: "live", label: "Website", url: "https://shopslc.com/", iconKey: "globe" }],
    previewImage: "https://i.ibb.co/Y4B7qb8S/SLC.png",
  },
  {
    id: "purly-care",
    title: "Purly Care",
    summary:
      "Fully customising Shopify theme to match the client's branding, including layout, colours, fonts, and imagery.",
    status: "active",
    periodLabel: "2024 - 2025",
    technologies: [
      "HTML5",
      "CSS",
      "JavaScript",
      "Shopify",
      "Shopify Customization",
      "Liquid Template Language",
      "App Integrations",
      "Site Optimization",
    ],
    primaryUrl: "https://purlycare.com/",
    logo: SHOPIFY_GLYPH_LOGO,
    links: [{ kind: "live", label: "Website", url: "https://purlycare.com/", iconKey: "globe" }],
    previewImage: "https://i.ibb.co/hJBtd2jp/Purly-Care.png",
  },
  {
    id: "dcotstar",
    title: "Dcotstar",
    summary:
      "Designed and developed a store from scratch, crafting the UI/UX and implementing complete customization to deliver a unique and tailored eCommerce experience.",
    status: "active",
    periodLabel: "2023 - 2024",
    technologies: [
      "HTML5",
      "CSS",
      "JavaScript",
      "Shopify",
      "Shopify Customization",
      "Liquid Template Language",
    ],
    primaryUrl: "https://dcotstar.com/",
    logo: SHOPIFY_GLYPH_LOGO,
    links: [{ kind: "live", label: "Website", url: "https://dcotstar.com/", iconKey: "globe" }],
    previewImage: "https://i.ibb.co/3mg3MmVs/Dcotstar.png",
  },
];
